- changes/unreleased/Added-20220902-112333.yaml
- cmd/metadata.go
- cmd/root.go
- pkg/engine/engine.go
This PR adds an `Engine.Metadata` method which returns the metadata of all of its polices.
> feat: CLOUD-727 method to extract all policy metadata

- LICENSE
- changes/unreleased/Fixed-20220902-123031.yaml
This PR changes the format of LICENSE so that (hopefully) it'll be recognized properly by GitHub and go.dev.
> fix: license formatting

- changes/unreleased/Changed-20220906-144018.yaml
- docs/library_usage.md
- pkg/engine/engine.go
BREAKING CHANGE: ResourcesResolvers were previously injected into
EngineOptions, but weren't used until Eval(), at which time they were
transposed to EvalOptions. This starts to matter when we need to run
Eval() more than once but with different ResourcesResolver chains, in
order to compare results, and want to avoid duplicating the work done at
NewEngine() time.
---
Needed for https://snyksec.atlassian.net/browse/CTX-403, but only tenuously related to that.
As far as we know, cloud context scans are the only current use case of ResourcesResolvers, and we're happy to consume our own breaking change. We could write this in a non-breaking way, by adding a duplicate field to EvalOptions and having it supersede EngineOptions, but this feels unnecessary.
Paired with @moadibfr
> [CTX-403] feat: move ResourcesResolver injection to eval time

- changes/unreleased/Added-20220914-151249.yaml
- docs/library_usage.md
- pkg/postprocess/custom_severities.go
- pkg/postprocess/custom_severities_test.go
- swagger.yaml
Even though the code is very simple, we want to apply custom severities in a number
of different places in our codebase, so it seems good to share the logic.
> [CLOUD-673] Add postprocess.ApplyCustomSeverities

- changes/unreleased/Added-20220907-154554.yaml
- docs/policy_authoring.md
- docs/policy_spec.md
- docs/proposals.md
- examples/09-secondary-resource-deny.rego
- examples/main.tf
- pkg/policy/base.go
- pkg/policy/multi.go
This PR adds support for the primary_resource attribute in deny rules. This implements the Rego API changes needed to enable "secondary resource denies" as described in https://github.com/snyk/policy-engine/pull/114
The rest of that proposal requires breaking changes to the output format, which will be addressed in separate PRs. I've added a small document with a table to track the status of that proposal as well as future proposals.
> feat: CLOUD-795 rego API support for secondary resource deny

- changes/unreleased/Added-20220918-162606.yaml
- docs/policy_spec.md
- pkg/policy/base.go
To support the work of [filtering policies by product tag in the new Settings Page](https://snyksec.atlassian.net/browse/CFG-2147) we need to add to the PE `Metadata` structure type the new `product` field that was recently added.
@jason-snyk / @jaspervdj-snyk if I understand the code correctly this is the only change needed to add support for a new metadata field, if this is not the case please let me know :)
> feat: add `product` metadata field

- changes/unreleased/Fixed-20220927-154157.yaml
- rego/snyk.rego
- rego/snyk_test.rego
The pure rego implementation leaves .id as-is when it is already set in the attributes.  This differs from the Go implementation in `resourceStateToRegoInput` which is problematic.
> fix: resource .id in repl/test

- changes/unreleased/Added-20220927-133054.yaml
- pkg/hcl_interpreter/moduletree.go
- pkg/input/golden_test/tf/cdktf.out.json
- pkg/input/golden_test/tf/cdktf.out/frontend-dev.tf.json
- pkg/input/golden_test/tf/cdktf.out/posts-dev.tf.json
- pkg/input/golden_test/tf/tfjson.json
- pkg/input/golden_test/tf/tfjson/main.tf.json
- pkg/input/tf.go
This PR adds support for `.tf.json` files to the existing TF detector. This is the extension that Terraform recognizes for its JSON syntax: https://www.terraform.io/language/syntax/json
> Terraform expects native syntax for files named with a `.tf` suffix, and JSON syntax for files named with a `.tf.json` suffix.
This will also enable us to support the output of `cdktf synth`.
> feat: add support for .tf.json files

- changes/unreleased/Fixed-20220928-180822.yaml
- pkg/input/golden_test/tfstate/data-01.json
- pkg/input/golden_test/tfstate/ids-01.json
- pkg/input/tfstate.go
This PR resolves an issue with duplicate resource IDs from the tfstate detector. There are some resource types where `id` can be non-unique. Using `<resource_type>.<resource_name>` produces unique IDs that match our HCL and tfplan detectors.
> fix: duplicate resource IDs in tfstate

- changes/unreleased/Added-20220930-105218.yaml
- docs/policy_spec.md
- pkg/policy/api.go
- rego/snyk.rego
- rego/snyk_test.rego
This PR changes the way the resource's `id` property is set in our Rego API so that it will contain the "physical ID" if one is defined. Otherwise, it will be set to the logical ID.
We've also added an `_id` attribute which will _always_ be set to the "logical ID". In general, we should use `_id` when dealing with Terraform data resources.
> feat: retain physical id when defined and add _id attribute

- .gitignore
- changes/unreleased/Fixed-20221004-191109.yaml
- cmd/test.go
This PR enables `print()` statements. The option `CapturePrintOutput()` on the test runner is a no-op, and in order for the output to be captured, it's necessary to enable the `WithEnablePrintStatements()` option on the compiler.
> Enable print() statements

- changes/unreleased/Fixed-20221005-114127.yaml
- pkg/engine/engine.go
The `Logger` configured on the `Engine` was not correctly propagated into the `EvalOptions`. In case of errors, log messages were sent to the default logger (stderr) instead of to the configured one.
> Use the configured Engine logger when evaluating policies

- changes/unreleased/Fixed-20221019-144350.yaml
- pkg/input/tf.go
When an HCL evaluation fails, the Policy Engine should return a `FailedToParseInput` error, so callers can properly handle it.
> Return a FailedToParseInput error if an HCL evaluation fails

- changes/unreleased/Fixed-20221103-160316.yaml
- pkg/policy/base.go
This PR changes the ID that we use when we deserialize rule results after evaluation. The `_id` property will always be the `Resource.ID`, whereas the `id` property can come from the resource's attributes if they have an `id` property. Consumers always expect that we return the `Resource.ID` in the `resource_id` field in rule results, so this change fulfills that expectation.
> fix: CLOUD-972 use _id in rule result builder

- changes/unreleased/Fixed-20221208-124721.yaml
- rego/snyk/internal/relations_test.rego
- rego/snyk/relations.rego
This is what's in the spec, and it leads to less surprising results if you do things like `count(_)==0`.
> fix: return empty arrays from snyk.[back_]relates

- changes/unreleased/Fixed-20221213-132318.yaml
- cmd/root.go
- main.go
This change returns a non-zero exit code when an error occurs.
Old:
```
± policy-engine foo
Error: unknown command "foo" for "policy-engine"
Run 'policy-engine --help' for usage.
± echo $?
0
```
New:
```
± policy-engine foo
Error: unknown command "foo" for "policy-engine"
Run 'policy-engine --help' for usage.
± echo $?
2
```
Old:
```
± policy-engine test -p -d rego/lib
Error: unknown shorthand flag: 'p' in -p
Usage:
policy-engine test [flags]
Flags:
-f, --filter string      Regular expression to filter tests by.
-h, --help               help for test
--update-snapshots   Updates snapshots used in snapshot_testing.match
Global Flags:
-d, --data strings   Rego paths to load
-v, --verbose        Sets log level to DEBUG
± echo $?
0
```
New:
```
± policy-engine test -p -d rego/lib
Error: …
```
> fix: return non-zero if a command throws error

- Makefile
- changes/unreleased/Changed-20221215-080749.yaml
- docs/policy_spec.md
- examples/metadata/rules/snyk_001/metadata.json
- examples/metadata/rules/snyk_007/metadata.json
- pkg/engine/engine.go
- pkg/models/compat.go
- pkg/models/json_test.go
- pkg/models/model_rule_results.go
- pkg/policy/base.go
- swagger.yaml
- test/examples_test.json
This takes some precautions that models and metadata are still serializable from older formats
> feat: array based format for compliance controls

- changes/unreleased/Fixed-20230105-232252.yaml
- pkg/data/provider.go
On Linux, with a soft nofile limit of 1024, I was consistently getting errors for repositories with many rego files.  This fixes that by closing the file handles as soon as we've parsed the files.
> fix: too many open files

- changes/unreleased/Changed-20230111-120801.yaml
- pkg/hcl_interpreter/hcl_interpreter.go
- pkg/input/tf.go
I was working on using the hcl_interpreter library in Regula, and found it hard to access certain fields that we're currently populating there (`_filepath`, `_provider`).  This change exports a little more resource information for consumers of hcl_interpreter.
> feat: export more resource info from hcl_interpreter

- changes/unreleased/Fixed-20230203-133834.yaml
- pkg/engine/engine.go
- pkg/policy/base.go
- pkg/policy/multi.go
This PR makes it so that we no-longer set `input` for multi-resource policies. The conversion between our structs and OPA's representation is too costly for large inputs. Instead, policy authors should interact with resources from the input via the `snyk.resources()` function, which does not rely on `input` being set.
> fix: CLOUD-1168 remove input for multi-resource policies

- changes/unreleased/Added-20230110-120307.yaml
- cmd/eval.go
- cmd/fixture.go
- cmd/metadata.go
- cmd/root.go
- cmd/run.go
- cmd/test.go
The `-i command` flag is useful, but the REPL continues to run which makes it unfit for use in scripts.  We can add a `-c command` to get something closer to `opa eval`.
> feat: add -c to repl command (CLOUD-1088)

- changes/unreleased/Fixed-20230208-164224.yaml
- pkg/policy/multi.go
There are some existing policies that use a pattern that redefines `input`, like:
```open-policy-engine
deny = ret {
ret = some_lib.deny with input as {
"resources": input.resources,
"some_param": "foo",
}
}
```
The `"resources": input.resources` is necessary in order to test these policies, because `policy-engine test` uses a pure rego implementation of `snyk.resources` that reads from `input`.
The `resources` entries are otherwise unused, so this PR sets a fake input document in multi-resource policies so that policies written like the above will continue to work.
> fix: CLOUD-1168 use empty input to not break some existing policies

- .github/workflows/changelog.yml
- .github/workflows/release.yml
- .github/workflows/release_candidate.yml
- .github/workflows/tag_release_version.yml
- .github/workflows/test.yaml
- Makefile
- changes/unreleased/Changed-20230208-123940.yaml
* `release_candidate`: new workflow that runs on release branches and tries
to do a `goreleaser build.
* `tag_release_version`: new workflow that runs when a `release/*` branch is
merged and tags the version.
* Update `actions/checkout` action to `v3`
* Update `actions/setup-go` action to v3
* Update use of deprecated `::set-output` to `$GITHUB_OUTPUT`
> chore: improve release process (CLOUD-1178)

- changes/unreleased/Changed-20230217-114716.yaml
- pkg/engine/engine.go
- pkg/logging/logger.go
- pkg/policy/legacyiac.go
- pkg/policy/multi.go
- pkg/policy/single.go
The default structured logging is turning out to be a nuisance. This PR adds a new `NopLogger` and changes the default behavior so that logging is disabled when a logger is not provided.
> fix: disable logging by default

- changes/unreleased/Added-20230221-173748.yaml
- cmd/fixture.go
- cmd/root.go
- cmd/test.go
- cmd/verbosity.go
- go.mod
This adds a `--log-level` flag, that can be set to `debug`, `info`, `warn` or `error`.
The existing `--verbose` (`-v`) flag becomes equivalent to setting `--log-level debug`.
If both `--verbose` and `--log-level` are set, then we validate that `--log-level` is set to `debug` for consistency.
> feat: add --log-level flag

- changes/unreleased/Fixed-20230310-192411.yaml
- pkg/bundle/v1/test_inputs/complete/lib/utils.rego
The library was failing on a null bucket_prefix in cloud scan
> fix: update complete example bundle

- changes/unreleased/Fixed-20230426-132720.yaml
- pkg/policy/base.go
- pkg/policy/factory.go
- pkg/policy/legacyiac.go
- pkg/policy/multi.go
- pkg/policy/single.go
- test/e2e_test.go
- test/regression.json
- test/regression/norulekey.rego
In #193 we added some code to make `query()` return different queries based on whether or not the underlying rule has a key.
For example, it would return:
-   the query `deny` for the rule `deny { false }`
-   the query `deny[_]` for the rule `deny[info] { info = "foo" }`
However, this is inherently flawed since it is purely based on the syntax of the underlying rule, and not its semantics.  For examples, these two shapes of rules should be handled the same way:
-   `deny[info] { ... }`
-   `deny = library.make_deny(...)`
The code interpreting the result _already knows_ if it's expecting a set or a single result, and that's what the query should be based on -- not the syntax of the rule.
To fix this, I added two queries, `query` and `queryElem`.
---
When researching other uses of …
> fix: deny parsing for key-less rules (CLOUD-1433)

- changes/unreleased/Fixed-20230426-081611.yaml
- pkg/input/cloudapi/client.go
- pkg/input/cloudapi/client_test.go
This PR fixes a bug where paths in ClientConfig.URL were being removed. Some Snyk environments require a path, e.g. `/api`, so we need to retain the path in the sanitized URL.
> fix: allow path in ClientConfig.URL

- changes/unreleased/Fixed-20230427-152428.yaml
- pkg/policy/ruleresultbuilder.go
This PR fixes a bug where rules without messages would produce messages that only contained newlines, like `"\n\n"` if they produced multiple results.
> fix: messages produced by rules without messages

- changes/unreleased/Added-20230501-160449.yaml
- pkg/hcl_interpreter/errors.go
- pkg/hcl_interpreter/hcl_interpreter.go
- pkg/hcl_interpreter/moduletree.go
- pkg/hcl_interpreter/value.go
As part of the work to provide users of Snyk Integrated IaC a better output for non-fatal errors we need to create sentinel errors that the PE will produce and `snyk-iac-test` will consume and process. 
https://snyksec.atlassian.net/browse/CFG-2258
https://snyksec.atlassian.net/browse/CLOUD-1439
> feat: add sentinel errors for non fatal errors [CLOUD-1439]

- changes/unreleased/Added-20230509-120632.yaml
- pkg/hcl_interpreter/errors.go
- pkg/hcl_interpreter/moduletree.go
Following the chat [here](https://snyk.slack.com/archives/C04CQ0D2VFH/p1683556057785469), I've added a new sentinel error when we get an error when loading a submodule.
> feat: new sentinel error for loading submodule error

- changes/unreleased/Added-20230509-100822.yaml
- cmd/version.go
- pkg/version/version.go
```
> go build && ./policy-engine version
Version:           unknown-version
OPA Version:       0.46.0-dev
Terraform Version: 1.3.8
Revision:          949acd82eb01ba1cd306730804def2b81f12e371*
```
> feat: expose the embedded version info for terraform

- changes/unreleased/Fixed-20230525-111249.yaml
- cmd/cloud.go
- cmd/verbosity.go
- pkg/input/cloud_loader.go
- pkg/input/cloud_loader_test.go
- pkg/input/cloudapi/client.go
- pkg/input/cloudapi/client_test.go
- pkg/input/cloudapi/resources.go
- pkg/input/cloudapi/resources_test.go
- pkg/input/golden_test/tf/dynamic-block-william/terraform.tf
- pkg/input/golden_test/tf/dynamic-block-william/variables.tf
- pkg/input/golden_test/tf/dynamic-block/dynamic-block.tf
- pkg/input/golden_test/tf/regula-issue-397/main.tf
- pkg/internal/withtimeout/do.go
- pkg/policy/allowlist.go
- pkg/policy/api_test.go
- pkg/rego/bind.go
- pkg/rego/bind_test.go
- pkg/rego/query.go
- pkg/rego/query_test.go
- scripts/license.py
This PR fixes a tiny bug in the license script and updates the license blocks wherever needed.
> chore: update and run license script

- changes/unreleased/Changed-20230530-095629.yaml
- swagger.yaml
This commit renames the informational severity to info in order to align with Snyk.
This change has no functional effect within `policy-engine`, but could affect clients generated from these specs.
> refactor: CLOUD-1495 rename informational severity to info

- changes/unreleased/Fixed-20230530-160602.yaml
- pkg/models/compat.go
- pkg/policy/base.go
- test/examples.json
- test/fuguerules.json
- test/regression.json
This PR fixes a bug where rule results that are unmarshalled using the model classes that we provide were missing the Kind and RuleBundle fields.
It also fixes a logic bug that caused Kind to be missing when no metadata rule was defined.
The unmarshal bug was quite tricky, because new metadata and rule result fields have to be added in a few places. We should follow up with a longer term fix that removes the backwards compatibility code, because it's no longer needed. That means that we'll also need to go through every consumer to ensure that all test data has been updated.
> fix: CLOUD-1495 missing rule result fields

- changes/unreleased/Fixed-20240725-160823.yaml
- pkg/hcl_interpreter/source_locations.go
- pkg/input/golden_location_test.go
- pkg/input/golden_test/tf/count-simple.json
- pkg/input/golden_test/tf/count-simple/main.tf
When computing a resource location a regex is used to strip the brackets from a resource ID.
E.g. `aws_s3_bucket.example[1]` stripped of brackets is  `aws_s3_bucket.example`
The regex used was not working when an ID had multiple chars inside brackets.
> fix: account for multiple chars in resource id[IAC-3015]

- changes/unreleased/Added-20241128-171516.yaml
- docs/policy_spec.md
- examples/12-context.rego
- pkg/policy/base.go
- pkg/policy/fugue.go
- pkg/policy/multi.go
- pkg/policy/ruleresultbuilder.go
- pkg/policy/single.go
- test/examples.json
Added support for a user-defined free form output for the single-resource and multi-resource policy types.
Potential use case: providing customized evidence based on resource values in policy "passed" outputs.
See `examples/12-context.rego`
> feat: support for user-defined policy output [IAC-3161]

- changes/unreleased/Security-20250227-134037.yaml
- go.mod
- go.sum
Addressing new vuln https://security.snyk.io/vuln/SNYK-GOLANG-GOLANGORGXOAUTH2JWS-8749594.
> fix: upgrade to oauth2/jws 0.27.0 [IAC-3242]

- CHANGELOG.md
- changes/unreleased/Changed-20250513-154933.yaml
- changes/v0.34.0.md
Breaking changes are introduced
Rego rules need to be upgraded in order to work with policy-engine
> Bump version to v0.34.0
